apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      isDefault: true
